{% set version = "0.50" %}

package:
  name: perl-capture-tiny
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/Capture-Tiny-{{ version }}.tar.gz
  sha256: ca6e8d7ce7471c2be54e1009f64c367d7ee233a2894cacf52ebe6f53b04e81e5

build:
  number: 0
  script: "perl Makefile.PL INSTALLDIRS=site && make && make test && make install"
  skip: true  # [win]

requirements:
  build:
    - make
  host:
    - perl
  run:
    - perl

test:
  imports:
    - Capture::Tiny

about:
  home: https://github.com/dagolden/Capture-Tiny
  license: Artistic-2.0
  summary: 'Capture STDOUT and STDERR from Perl, XS or external programs'

extra:
  recipe-maintainers:
    - '0xaf1f'
